import { mkdir, writeFile } from "node:fs/promises";
import { config } from "./config.js";

const token = process.env.GITHUB_TOKEN;
if (!token) throw new Error("GITHUB_TOKEN is required");

const headers = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  Authorization: "Bearer " + token
};

async function github(path) {
  const response = await fetch("https://api.github.com" + path, { headers });
  if (!response.ok) {
    throw new Error("GitHub API " + response.status + ": " + await response.text());
  }
  return response.json();
}

const esc = (value) => String(value ?? "")
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

const user = await github("/users/" + config.username);
const repos = (await github("/users/" + config.username + "/repos?per_page=100&sort=updated"))
  .filter((repo) => !repo.fork);

const totalStars = repos.reduce((sum, repo) => sum + repo.stargazers_count, 0);
const totalForks = repos.reduce((sum, repo) => sum + repo.forks_count, 0);
const languages = [...new Set(repos.map((repo) => repo.language).filter(Boolean))];
const repoByName = new Map(repos.map((repo) => [repo.name, repo]));
const lastUpdated = repos[0]?.pushed_at ? repos[0].pushed_at.slice(0, 10) : "now";

await mkdir("assets", { recursive: true });
await mkdir("generated", { recursive: true });

// Neon / cyberpunk banner inspired by the supplied profile pack.
const bannerSvg = [
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 400" width="1200" height="400">',
  '<defs>',
  '<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">',
  '<stop offset="0" stop-color="#0a0416"/><stop offset="0.55" stop-color="#19052f"/><stop offset="1" stop-color="#06131d"/>',
  '</linearGradient>',
  '<linearGradient id="neon" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#ff2a6d"/><stop offset="0.5" stop-color="#ff2a6d"/><stop offset="1" stop-color="#05d9e8"/></linearGradient>',
  '<filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>',
  '</defs>',
  '<rect width="1200" height="400" rx="24" fill="url(#bg)"/>',
  '<g opacity=".35" stroke="#05d9e8">',
  '<path d="M0 320L260 80M170 400L520 60M480 400L830 40M760 400L1120 40" stroke-width="1"/>',
  '</g>',
  '<g fill="#f5f0ff" opacity=".75">',
  '<circle cx="90" cy="88" r="2"/><circle cx="182" cy="142" r="1.5"/><circle cx="932" cy="82" r="1.5"/><circle cx="1040" cy="130" r="2"/><circle cx="1110" cy="64" r="1.4"/><circle cx="778" cy="54" r="1.2"/>',
  '</g>',
  '<rect x="46" y="45" width="1108" height="310" rx="18" fill="none" stroke="#2c183b"/>',
  '<text x="88" y="138" font-family="Courier New, monospace" font-size="56" font-weight="700" letter-spacing="3" fill="#f5f0ff">THARUN SHAMALAN</text>',
  '<text x="92" y="180" font-family="Courier New, monospace" font-size="21" letter-spacing="1.4" fill="#d9c8ff">SOC ANALYST • MSSP • CHENNAI</text>',
  '<rect x="92" y="204" width="520" height="3" fill="url(#neon)" filter="url(#glow)"/>',
  '<text x="92" y="244" font-family="Courier New, monospace" font-size="17" fill="#c5b5df">ALERT TRIAGE • DETECTION • AUTOMATION • IR</text>',
  '<text x="92" y="286" font-family="Courier New, monospace" font-size="15" fill="#7c8aa6">ATTACK TELEMETRY → DETECT → INVESTIGATE → RESPOND</text>',
  '<circle cx="1010" cy="198" r="88" fill="#150432" stroke="#ff2a6d" stroke-width="2"/>',
  '<circle cx="1010" cy="198" r="70" fill="none" stroke="#05d9e8" stroke-width="1" opacity=".7"/>',
  '<path d="M966 238L994 208L1012 220L1053 169" fill="none" stroke="#39ff88" stroke-width="5" filter="url(#glow)"/>',
  '<circle cx="966" cy="238" r="5" fill="#39ff88"/><circle cx="1012" cy="220" r="5" fill="#39ff88"/><circle cx="1053" cy="169" r="5" fill="#39ff88"/>',
  '<text x="1010" y="205" text-anchor="middle" font-family="Courier New, monospace" font-size="13" fill="#f5f0ff">SOC</text>',
  '<text x="92" y="332" font-family="Courier New, monospace" font-size="12" fill="#718096">PROFILE_STATUS: ONLINE // DATA: GITHUB API // MODE: AUTOGENERATED</text>',
  '</svg>'
].join("");

const metricsCards = config.work.impact.map((card, index) => {
  const x = index * 244 + 6;
  const stroke = index % 2 === 0 ? "#ff2a6d" : "#05d9e8";
  return [
    '<g transform="translate(' + x + ',6)">',
    '<rect x="1" y="1" width="232" height="146" rx="10" fill="#150432" stroke="' + stroke + '" stroke-width="1.6"/>',
    '<text x="116" y="60" text-anchor="middle" font-family="Courier New, monospace" font-size="43" font-weight="700" fill="#f5f0ff">' + esc(card[0]) + "</text>",
    '<text x="116" y="95" text-anchor="middle" font-family="Courier New, monospace" font-size="12" fill="#d9c8ff">' + esc(card[1]) + "</text>",
    '<text x="116" y="118" text-anchor="middle" font-family="Courier New, monospace" font-size="12" fill="#a88bc8">' + esc(card[2]) + "</text>",
    "</g>"
  ].join("");
}).join("");

const metricsSvg = [
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1230 158" width="1230" height="158">',
  '<rect width="1230" height="158" rx="14" fill="#08030f"/>',
  '<g font-family="Courier New, monospace">',
  metricsCards,
  "</g>",
  "</svg>"
].join("");

const dividerSvg = [
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 24" width="1200" height="24">',
  '<defs><linearGradient id="l" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#ff2a6d" stop-opacity="0"/><stop offset=".3" stop-color="#ff2a6d"/><stop offset=".7" stop-color="#05d9e8"/><stop offset="1" stop-color="#05d9e8" stop-opacity="0"/></linearGradient></defs>',
  '<rect y="11" width="1200" height="2" fill="url(#l)"/>',
  '<rect x="594" y="6" width="12" height="12" transform="rotate(45 600 12)" fill="#0d0221" stroke="#f5f0ff" stroke-width="1.6"/>',
  "</svg>"
].join("");

const projectMapSvg = [
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 380" width="1200" height="380">',
  '<rect width="1200" height="380" rx="18" fill="#08030f"/>',
  '<text x="54" y="42" font-family="Courier New, monospace" font-size="15" fill="#718096">PROJECT DNA // WHAT I BUILD</text>',
  '<line x1="54" y1="60" x2="1146" y2="60" stroke="#2c183b"/>',
  '<g font-family="Courier New, monospace">',
  '<rect x="54" y="92" width="220" height="84" rx="12" fill="#120725" stroke="#ff2a6d"/><text x="70" y="120" font-size="12" fill="#ff2a6d">01 // CLOUD</text><text x="70" y="145" font-size="13" fill="#f5f0ff">HONEYPOT → SENTINEL</text><text x="70" y="164" font-size="11" fill="#a88bc8">attack telemetry + geolocation</text>',
  '<rect x="296" y="92" width="220" height="84" rx="12" fill="#120725" stroke="#05d9e8"/><text x="312" y="120" font-size="12" fill="#05d9e8">02 // ENDPOINT</text><text x="312" y="145" font-size="13" fill="#f5f0ff">WAZUH → MITRE</text><text x="312" y="164" font-size="11" fill="#a88bc8">monitoring + detection evidence</text>',
  '<rect x="538" y="92" width="220" height="84" rx="12" fill="#120725" stroke="#39ff88"/><text x="554" y="120" font-size="12" fill="#39ff88">03 // API</text><text x="554" y="145" font-size="13" fill="#f5f0ff">AUTH → RBAC → SIEM</text><text x="554" y="164" font-size="11" fill="#a88bc8">defensive lifecycle design</text>',
  '<rect x="780" y="92" width="220" height="84" rx="12" fill="#120725" stroke="#ff2a6d"/><text x="796" y="120" font-size="12" fill="#ff2a6d">04 // MALWARE</text><text x="796" y="145" font-size="13" fill="#f5f0ff">POWERSHELL → ATT&amp;CK</text><text x="796" y="164" font-size="11" fill="#a88bc8">loader analysis + behavior</text>',
  '<rect x="1022" y="92" width="124" height="84" rx="12" fill="#120725" stroke="#05d9e8"/><text x="1036" y="120" font-size="12" fill="#05d9e8">05 // RECON</text><text x="1036" y="145" font-size="11" fill="#f5f0ff">PIPELINES</text><text x="1036" y="164" font-size="10" fill="#a88bc8">automation</text>',
  '<text x="54" y="228" font-size="13" fill="#718096">COMMON THREAD</text>',
  '<text x="54" y="266" font-size="19" fill="#f5f0ff">ATTACK / SIMULATE</text><text x="270" y="266" font-size="19" fill="#05d9e8">→</text><text x="310" y="266" font-size="19" fill="#f5f0ff">COLLECT TELEMETRY</text><text x="560" y="266" font-size="19" fill="#05d9e8">→</text><text x="598" y="266" font-size="19" fill="#f5f0ff">DETECT</text><text x="702" y="266" font-size="19" fill="#05d9e8">→</text><text x="740" y="266" font-size="19" fill="#39ff88">RESPOND</text>',
  '<rect x="54" y="302" width="1092" height="2" fill="#2c183b"/>',
  '<text x="54" y="334" font-size="12" fill="#718096">REPO SIGNAL:</text><text x="154" y="334" font-size="12" fill="#d9c8ff">' + esc(languages.slice(0, 6).join("  ·  ") || "SCANNING") + "</text>",
  "</g></svg>"
].join("");

await writeFile("assets/banner.svg", bannerSvg);
await writeFile("assets/divider.svg", dividerSvg);
await writeFile("generated/metrics.svg", metricsSvg);
await writeFile("generated/project-map.svg", projectMapSvg);

const projectRows = config.projects.map((project) => {
  const repo = repoByName.get(project.repo);
  const href = repo?.html_url || ("https://github.com/" + config.username + "/" + project.repo);
  const signal = repo ? (repo.language || "Security") + " · ★ " + repo.stargazers_count : project.theme;
  return "<tr><td width=\"34%\"><h3><a href=\"" + href + "\">" + esc(project.name) + "</a></h3><sub>" + esc(project.theme) + "</sub></td><td>" + esc(project.description) + "<br><br><sub>" + esc(signal) + "</sub></td></tr>";
}).join("\n");

const stack = config.stack.map((item) => {
  return "<img src=\"https://img.shields.io/badge/" + encodeURIComponent(item).replaceAll("%20", "-") + "-150432?style=for-the-badge&labelColor=0d0221\" alt=\"" + esc(item) + "\">";
}).join(" ");

const focus = config.focus.map((item) => "- **" + esc(item) + "**").join("  \n");
const credentials = config.credentials.map((item) => "- **" + esc(item[0]) + "** — " + esc(item[1])).join("\n");
const awards = config.awards.map((item) => "- **" + esc(item[0]) + "** — " + esc(item[1])).join("\n");

const readme = [
  '<div align="center">',
  '  <img src="https://github.com/Tharunehh.png?size=256" width="150" alt="Tharun Shamalan">',
  '  <br><br>',
  '  <img src="assets/banner.svg" alt="Tharun Shamalan, SOC analyst at an MSSP in Chennai" width="100%">',
  "</div>",
  "",
  "<div align=\"center\">",
  "",
  "I work in a SOC at a managed security services provider, so my days are spent deciding which alerts are real across customer environments. I triage in Microsoft Sentinel, FortiSIEM and Rapid7 InsightIDR, escalate what's confirmed, and spend the rest of my time making the next alert easier to judge: tuning detections, automating repetitive steps and feeding threat intel back into the pipeline.",
  "",
  '<a href="' + config.links.portfolio + '">Portfolio</a> · <a href="' + config.links.linkedin + '">LinkedIn</a> · <a href="https://github.com/' + config.username + '">GitHub</a>',
  "",
  "</div>",
  "",
  '<div align="center"><img src="generated/metrics.svg" alt="Security impact metrics" width="100%"></div>',
  '<div align="center"><img src="assets/divider.svg" alt="" width="100%"></div>',
  "",
  "## What I do at work",
  "",
  "**Investigation.** " + config.work.investigations,
  "",
  "**Automation.** " + config.work.automation,
  "",
  "**Detection.** " + config.work.detection,
  "",
  "**Threat intel and awareness.** " + config.work.threatIntel,
  "",
  "I also write recurring security reports covering alerts, trends and where customer posture can improve.",
  "",
  '<div align="center"><img src="assets/divider.svg" alt="" width="100%"></div>',
  "",
  "## Lab projects",
  "",
  "I build these to practice what I don't get to touch every day. Each repository is a focused security exercise with implementation details and evidence.",
  "",
  '<img src="generated/project-map.svg" alt="Project DNA" width="100%">',
  "",
  "<table>",
  projectRows,
  "</table>",
  "",
  '<div align="center"><img src="assets/divider.svg" alt="" width="100%"></div>',
  "",
  "## Focus areas",
  "",
  focus,
  "",
  "## Tools I use",
  "",
  stack,
  "",
  "## Credentials",
  "",
  credentials,
  "",
  awards,
  "",
  '<div align="center"><img src="assets/divider.svg" alt="" width="100%"></div>',
  "",
  "## Live GitHub telemetry",
  "",
  "- **" + repos.length + "** owned public repositories",
  "- **" + user.followers + "** followers",
  "- **" + totalStars + "** total stars across owned non-fork repositories",
  "- **" + totalForks + "** forks across owned non-fork repositories",
  "- **" + esc(languages.join(", ") || "Not detected") + "** primary languages",
  "- Last repository activity observed: **" + lastUpdated + "**",
  "",
  '<div align="center">',
  '<sub>This profile is generated automatically from GitHub data.</sub>',
  "</div>",
  ""
].join("\n");

await writeFile("README.md", readme);
console.log("Generated profile for " + config.username + ": " + repos.length + " repos, " + totalStars + " stars.");
